### ISSUE TITLE
subscript issues

### ISSUE THREAD

**Issue by privetin** [samueleblanc/MatTalX#1]
Alphabets b, c, d, f, g, q, w, y, and z cant seem to become subscripts.

**Comment by samueleblanc** [comment]
I know, as I'm aware, these are not yet Unicode characters (https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts). If I'm wrong, please tell me!

**Comment by privetin** [comment]
ah ofc. my bad. thanks for the tool!
